# Generated by Django 5.1.4 on 2025-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(blank=True, default='categories', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, default='client', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='date_project',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='project',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='meu_portfolio.imagem'),
        ),
    ]
